name: ewallet_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  carousel_slider: ^5.0.0
  change_case: ^2.2.0
  cupertino_icons: ^1.0.8
  dropdown_search: ^6.0.2
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.1.0
  flutter_sticky_header: ^0.8.0
  grouped_list: ^6.0.0
  flutter_timer_countdown: ^1.0.7
  font_awesome_flutter: ^10.12.0
  form_builder_validators: ^11.2.0
  get: ^4.6.6
  intl: ^0.20.2
  markdown_widget: ^2.3.2+8
  overlay_tooltip: ^0.2.3
  photo_view: ^0.15.0
  pinput: ^5.0.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  zoom_tap_animation: ^1.1.0
  lottie: ^3.3.2
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/intro/
    - assets/images/empty/
    - assets/images/logos/
    - assets/images/static/
    - assets/images/icons/3d/
    - assets/images/icons/gradient/
    - assets/images/dummy/
    - assets/fonts/
    - assets/animations/
  fonts:
    - family: Oxygen
      fonts:
        - asset: assets/fonts/Oxygen-Light.ttf
        - asset: assets/fonts/Oxygen-Regular.ttf
          weight: 500
        - asset: assets/fonts/Oxygen-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
